app/models/models.py
from flask import Blueprint
from flask_sqlalchemy import SQLAlchemy

models = Blueprint('models', __name__)


db = SQLAlchemy()


# Set up db model
class Todo(db.Model):
    id = db.Column(db.Integer, primary_key=True)
    content = db.Column(db.String(300), nullable=False)

    def __rep__(self):
        return '<Suggestion %r>' % self.id

app/forms/forms.py
from flask_wtf import FlaskForm
from wtforms import StringField, SubmitField
from wtforms.validators import InputRequired


class InputTodo(FlaskForm):
    """Todo Input form."""
    content = StringField(
        'Task',
        validators=[InputRequired()]
    )
    submit = SubmitField('Add task')


class ToDoActions(FlaskForm):
    """Todo Actions form."""
    update = SubmitField('Update')
    delete = SubmitField('Delete')

app/app.py
from flask import Flask, render_template, redirect, request, Blueprint
import os
from models.models import models, db
from routes.add_task import add_task
from routes.update_task import update_task
from routes.delete_task import delete_task
from forms.forms import InputTodo

# Get base directory
basedir = os.path.abspath(os.path.dirname(__file__))

app = Flask(__name__)

# Set up db config to local path
app.config['SQLALCHEMY_DATABASE_URI'] =\
    'sqlite:///' + os.path.join(basedir, 'test.db')

app.config['SECRET_KEY'] = 'secret'

# Register db model blueprint
app.register_blueprint(models)

# Register add task blueprint
app.register_blueprint(add_task)

# Register update task blueprint
app.register_blueprint(update_task)

# Register update task blueprint
app.register_blueprint(delete_task)

# Initialise db
db.init_app(app)
with app.app_context():
    db.create_all()

if __name__ == "__main__":
    app.run(debug=True)

app/routes/add_task.py
from flask import Blueprint, request, redirect, render_template
from forms.forms import InputTodo, ToDoActions
from models.models import db, Todo
import requests

add_task = Blueprint('add_task', __name__)

# Create homepage


@add_task.route('/', methods=['POST', 'GET'])
def home():
    # Get forms
    form = InputTodo()
    actions = ToDoActions()
    if request.method == 'POST':
        if form.validate_on_submit:
            todo = Todo(content=form.content.data)
            try:
                db.session.add(todo)
                db.session.commit()
                return redirect('/')
            except BaseException:
                return 'There was an error while adding the task'
    else:
        # Show all tasks
        tasks = Todo.query.all()
        # Show homepage with all tasks
        return render_template(
            "add_task.html",
            tasks=tasks,
            form=form,
            actions=actions)

app/routes/delete_task.py
from flask import Blueprint, request, redirect, render_template
from models.models import db, Todo
import requests

delete_task = Blueprint('delete_task', __name__)


@delete_task.route('/delete/<int:id>')
def delete(id):
    # Get ID of item to delete
    task_to_delete = Todo.query.get_or_404(id)
    try:
        db.session.delete(task_to_delete)
        db.session.commit()
        return redirect('/')
    except BaseException:
        return 'There was an error while deleting that task'

app/routes/update_task.py
from flask import Blueprint, request, redirect, render_template
from forms.forms import InputTodo, ToDoActions
from models.models import db, Todo
import requests

update_task = Blueprint('update_task', __name__)

# Create URL for updating task


@update_task.route('/update/<int:id>', methods=['GET', 'POST'])
def update(id):
    task = Todo.query.get_or_404(id)

    form = InputTodo()
    actions = ToDoActions()
    tasks = Todo.query.all()

    if request.method == 'POST':
        task.content = request.form['content']

        try:
            db.session.commit()
            # Return to homepage
            return redirect('/')
        except BaseException:
            return 'There was an issue while updating that task'

    else:
        # Show update task page
        return render_template(
            'update_task.html',
            tasks=tasks,
            task=task,
            form=form,
            actions=actions)

app/templates/add_task.html
{% extends 'home.html' %}

{% block container %}

<br>

<div class="text-center">
<form method="POST" action="/">
  {{ form.content.label }}
  {{ form.content }}
  {% if form.content.errors %}
    <ul>
        <li>{{ error }}</li>
    </ul>
    {% endif %}
    {{ form.submit }}

  </form>
</div>

{% endblock %}

app/templates/base.html
<html lang="en">
<head>
<title>To Do!</title>
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
<link rel="stylesheet" href="{{ url_for('static', filename='css/style.css') }}">
<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.6.0/jquery.min.js"></script>
<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.3.1/dist/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
</head>
<body>

<div class="header">
  <h1>To Do!</h1>
</div>

{% block content %}{% endblock %}

<script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/popper.js@1.14.7/dist/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@4.3.1/dist/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>

</body>
</html>

app/templates/home.html
{% extends 'base.html' %}

{% block content %}

{% block body %}{% endblock %}
 
<br>

<h2 class="text-center">To Do List!</h2>

<div class="center">
<table class="table" align="center">
  <thead>
    <tr>
      <th>
        Task
      </th>
      <th>
        Action
      </th>
    </tr>
  </thead>
  <tbody>
  {% for task in tasks %}
  <tr>
      <td>{{ task.content }}</td>
      <td>
        <button type="button" class="btn btn-light" onclick="window.location.href='update/{{task.id}}'">
          {{ actions.update.label}}
        </button>
        <button type="button" class="btn btn-light" data-toggle="modal" data-target="#deleteModal{{task.id}}">
          {{ actions.delete.label}}
        </button>

          <!-- Modal -->
          <div class="modal fade" id="deleteModal{{task.id}}" tabindex="-1" role="dialog" aria-labelledby="deleteModalLabel" aria-hidden="true">
            <div class="modal-dialog" role="document">
              <div class="modal-content">
                <div class="modal-body">
                  <p>Are you sure you want to delete the task {{ task.content }}</p>
                </div>
                <div class="modal-footer">
                  <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
                  <form action="{{url_for('delete_task.delete', id=task.id)}}">
                    <input type="submit" value="Delete" class="btn btn-danger">
                  </form>
                </div>
              </div>
            </div>
          </div>
      </td>
  </tr>
  {% endfor %}
    </tbody>
</table>
</div>

{% block container %} {% endblock %}

</body>
{% endblock %}
</html>

app/templates/update_task.html
{% extends 'home.html' %}

{% block body %}
<title>Edit Task</title>

<div class="text-center">
    <h1>Update Task</h1>
    <form action="/update/{{task.id}}" method="POST">
        <input type="text" name="content" id="content" value="{{task.content}}">
        <input type="submit" value="Update">
    </form>
</div>

{% endblock %}